version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9090:9090
    command: server /data
